- mautrix_facebook/portal.py
I added support for bridging facebook's ShareAttachments to Matrix.
This is useful when for example somebody sends an URL using facebook messenger and removes the URL from the text content while keeping the link preview. I assume similar behaviour can happen by sharing something through the facebook messenger app (not tested though). Currently the bridge just ignores share attachments (flagged as unsupported).
Just forwarding the share attachment as a separate matrix event can lead to duplicated URL previews on Riot (one preview for the URL in the message, and another one for the share attachment link). I implemented a fix by searching for URLs in the message body and ignoring ShareAttachments whose URL is already present in the message body.
@CromFr:matrix.org
> Support for sending facebook ShareAttachment to Matrix

- ROADMAP.md
Implemented in 113ec940290b172f0c19de4a95194aa6d777bdff and 1e5a7484decda9b2737a76eed3d3c2a4016ab134.
> Mention backfilling support in ROADMAP.md

- mautrix_facebook/user.py
- requirements.txt
Add application stats to core parts of facebook bridge!
> Add prometheus application stats

- mautrix_facebook/commands/auth.py
Improvement idea from https://github.com/tulir/mautrix-facebook/issues/10
Especially useful now that the "cookie method" is no longer possible
> Auth: redact login command

- mautrix_facebook/commands/auth.py
Fix the infinite loop of the enter_password() function if successfully logged in
> Fix infinite loop during authentification

- mautrix_facebook/example-config.yaml
- mautrix_facebook/portal.py
- requirements.txt
Requires https://github.com/mautrix/python/pull/66
> Use message send checkpoints

- mautrix_facebook/__main__.py
- mautrix_facebook/config.py
- mautrix_facebook/example-config.yaml
Quick change to enable randomising reconnect interval.
Config wise is this the right way to validate things? https://github.com/mautrix/facebook/commit/fcd1625d5441751b78e12f389e86cf1443d0cd61
> Random periodic reconnect interval

- mautrix_facebook/portal.py
> portal: send friendlier message when MQTT is disconnected

- mautrix_facebook/__main__.py
- mautrix_facebook/config.py
- mautrix_facebook/example-config.yaml
- mautrix_facebook/web/public.py
- mautrix_facebook/web/segment_analytics.py
Basic segment events for the public web views when a) the optional package is installed and b) the API key is present in an env var.
> Segment analytics

- mautrix_facebook/portal.py
> backfill: trim message list down to the limit if we go over

- mautrix_facebook/user.py
Prevents the bridge getting stuck with a bad proxy endlessly retrying it
without asking for a new one.
> Refresh proxy when getting transport errors reconnecting

- maufbapi/types/mqtt/message.py
> MentionType: add silent for messages with '/silent'

- mautrix_facebook/portal.py
Haven't tested yet (my local env is still stuck) but I think it should be pretty safe :)
> Use correct redaction event ID for MSS and checkpoints

- maufbapi/http/api.py
If we get a response error, then try to fetch the threads in the page one-at-a-time.
Once we arrive at a failing thread, find a timestamp earlier in history that works.
Note that this may cause some threads to be missed if they come close behind the failing thread, but since failures of this sort are probably rare, that's an acceptable tradeoff.
> thread fetch: search backwards to find next good timestamp

- mautrix_facebook/example-config.yaml
I swear I didn't come looking for smallfix bugs. I'd appreciate, if you'd add `hacktoberfest-accepted` label.
https://hacktoberfest.com/participation/#pr-mr-details
> config: fix typo

- maufbapi/types/graphql/__init__.py
- maufbapi/types/graphql/responses.py
- mautrix_facebook/puppet.py
> puppet: fix profile image downloading for IG users

- maufbapi/http/api.py
> backoff: fix bug when RLE hit

- mautrix_facebook/portal.py
- mautrix_facebook/user.py
> backfill: gate sending dummy, pre-backfill events on msc2716 support

- mautrix_facebook/portal.py
> backfill: make reaction and reply backfill work

- mautrix_facebook/__main__.py
> bridge bot: add contact info

- maufbapi/mqtt/conn.py
If these fail we potentially end up in a broken state where the connection is alive but messages don't flow.
> Always retry MQTT queue sync requests
